### ISSUE TITLE
How H was compute?

### ISSUE THREAD

**Issue by panecho** [zjudmd1015/icp#2]
@zjudmd1015 
I'm confused about the matrix H computed [ here](https://github.com/zjudmd1015/icp/blob/598d4af986766ca8013f7c12c527109c882d3f9a/icp.cpp#L35).
   H * A = B;  --> H = A' * B, any reference?
    Here A, B are corresponding point set, A' means A transpose, H is transform matrix;

**Comment by zjudmd** [comment]
You can refer to the derivation part of this original ICP paper (SVD approach), or some other papers mentioned on the [ICP Wiki page](https://en.wikipedia.org/wiki/Iterative_closest_point). 

> Arun, K.S., Huang, T.S. and Blostein, S.D., 1987. Least-squares fitting of two 3-D point sets. IEEE Transactions on pattern analysis and machine intelligence, (5), pp.698-700.

**Comment by panecho** [comment]
@zjudmd1015 
original paper dispels my confusion, tks.
